    [build-system]
    requires = ["setuptools>=61.0"]
    build-backend = "setuptools.build_meta"

    [project]
    name = "bolos"
    version = "0.1"
    description = "Python app used to solve two-term boltzmann equation"